### ISSUE TITLE
Does not work with Electron 15.3.1

### ISSUE THREAD

**Issue by Madriix** [saisandeepvaddi/electron-custom-menu-bar#13]
Does not work under Electron 15.3.1

```
renderer.js:22 Uncaught TypeError: window.openMenu is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:22)
2
renderer.js:26 Uncaught TypeError: window.minimizeWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:26)
renderer.js:32 Uncaught TypeError: window.maxUnmaxWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:32)
renderer.js:22 Uncaught TypeError: window.openMenu is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:22)
renderer.js:26 Uncaught TypeError: window.minimizeWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:26)
renderer.js:32 Uncaught TypeError: window.maxUnmaxWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:32)
renderer.js:42 Uncaught TypeError: window.closeWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:42)
```

Do you have any idea how to make it work?

**Comment by a2937** [comment]
Are you preloading the menu-functions.js file?
