### ISSUE TITLE
does not work with the version 24.2.0

### ISSUE THREAD

**Issue by royaljacques** [saisandeepvaddi/electron-custom-menu-bar#18]
Good morning
I have been trying for a while to use this code for a small project in order to discover a little bit the universe of electron. I have a problem:
```
renderer.js:27 Uncaught TypeError: window.minimizeWindow is not a function
    at HTMLButtonElement.<anonymous> (renderer.js:27:12)
(

```
I tried all possible things. so I noticed that the window is not modified. how could i change this?

**Comment by wh1ter0se** [comment]
Confirmed bug still exists on electron 30.0.8
